[#102] [#103] [UI] As a user, I can see the text field question and text area question
nmint8m/flutter-survey-app pull request #105
Opened 2023-03-07 07:15 UTC by nmint8m

- Close #102 #103 #32

## What happened 👀

The user can see the text field questions and text area question
The user can input answers.

## Insight 📝

N/A

## Proof Of Work 📹

<img width=300 src="https://user-images.githubusercontent.com/23162627/223350764-0ee9a71a-ce2d-4aa7-86bd-494066ce6f12.png">
<img width=300 src="https://user-images.githubusercontent.com/23162627/223350785-175aed79-f63c-47c8-ab4b-0151d9f7bbbd.png">

2023-03-08 04:04 UTC, manh-t requested changes

2023-03-08 04:04 UTC, manh-t commented on lib/views/answer/form/form_with_text_field_view.dart
> +          final controller = TextEditingController();
technically, we should create the controllers once in StatefulWidget. So putting the initialization in the `build` method will trigger the controller initialization multiple times. Can you put this in `initState` instead?

2023-03-08 04:04 UTC, manh-t commented on lib/views/answer/form/form_with_text_field_view.dart
> +          _controllers.add(controller);
same for the listeners

2023-03-09 09:59 UTC, manh-t commented on lib/views/answer/form/form_with_text_field_view.dart
> +    _buildControllers();
@nmint8m still, this method is in `build` 😓 Can't we set it in `initState`?
```
@override
  void initState() {
    // TODO: implement initState
    super.initState();
    Future.delayed(Duration(seconds: 0), () {
      _buildControllers();
    });
  }
```

2023-03-09 10:28 UTC, nmint8m commented
@manh-t Sure, I moved the code!

2023-03-10 04:23 UTC, manh-t approved these changes

2023-03-13 02:55 UTC, merged